tsc: Pass -b flag so that vite.config.ts is type checked
It highlighted the following error:

    [philbates@fedora laravel-starter]$ pnpm run build

    > @ build /home/philbates/code/philbates35/laravel-starter
    > tsc -b && vite build

    vite.config.ts:33:20 - error TS2461: Type 'string[] | undefined' is not an array type.

    33       exclude: [...configDefaults.coverage.exclude, ...projectExcludes],
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Found 1 error.